# Generated by Django 5.2.17 on 2026-10-04 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.TextField(blank=True, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('business_type', models.TextField(blank=True, null=True)),
                ('business_start_date', models.DateField(blank=True, null=True)),
                ('license', models.TextField(blank=True, null=True)),
                ('registration_number', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'organizations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TripEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_title', models.TextField()),
                ('event_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'trip entry',
                'verbose_name_plural': 'trip entries',
                'ordering': ['-event_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TripEntryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='trip_2027_files/')),
                ('file_name', models.TextField()),
                ('file_type', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('trip_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storefront.tripentry')),
            ],
            options={
                'verbose_name': 'trip entry file',
                'verbose_name_plural': 'trip entry files',
                'ordering': ['id'],
            },
        ),
    ]
